extends: spectral:oas
rules:
  info-contact: off

extends: spectral:oas
 
rules:
  no-delete-accounts::
    description: DELETE operations on accounts are not permitted
    severity: error
    given: "$.paths[*].delete"
    then:
      function: falsy
